@startuml
hide empty description
[*] --> :uninitialized
:uninitialized --> :initializing : Initialize
:uninitialized --> :uninitialized
:initializing --> :available
:initializing --> :uninitialized

state Running {
    :online --> :offline
    :online --> :unknown
    :offline --> :unknown
    :offline --> :online
    :unknown --> :offline
    :unknown --> :online
}

:available --> Running : Start
Running --> :available : Stop

@enduml